name: Windows

on:
  push:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        kind: [static, shared]
        runtimes: [MT, MD]

    runs-on: windows-2025

    concurrency:
        group: FRIKEE-${{ github.ref }}-${{ github.base_ref }}-${{ github.head_ref }}-Windows-2025-${{ matrix.kind }}-x64-${{ matrix.runtimes }}
        cancel-in-progress: true
    steps:
      - uses: actions/checkout@v1
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: branch@master
          actions-cache-folder: '.xmake-cache'
          actions-cache-key: 'windows'

      - name: Configure Pagefile
        uses: al-cheb/configure-pagefile-action@v1.4
        with:
          minimum-size: 8GB
          maximum-size: 32GB
          disk-root: "D:"

      - name: Tests
        run: |
          xmake --version
          xmake l ./scripts/test.lua -vD -a x64 -k ${{ matrix.kind }} --runtimes=${{ matrix.runtimes }} --linkjobs=2
